Review scripts

diff --git a/bin/go b/bin/go
--- a/bin/go
+++ b/bin/go
@@ -1,7 +1,13 @@
-#!/usr/bin/env bash
+#!/bin/bash
 #
-# 4E Website startup script
+# Startup script
 #
+
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && cd .. && pwd )"
+
+cd "$DIR" || echo 'cannot cd :('
+
+echo "Starting dev env in $DIR ..."
 
 docker-compose up -d
 
